myTable = read.table("household_power_consumption.txt", header=TRUE, sep=";", na.strings="?")
data <- subset(myTable, Date=="1/2/2007" | Date=="2/2/2007")
png(filename="plot1.png")
hist(data$Global_active_power,col="red",main="Global Active Power", xlab="Global Active Power (kilowatts)", ylab="Frequency", breaks=12)
dev.off()
