myTable = read.table("household_power_consumption.txt", header=TRUE, sep=";", na.strings="?")
data <- subset(myTable, Date=="1/2/2007" | Date=="2/2/2007")
x <- strptime(paste(as.character(data$Date), as.character(data$Time)),"%d/%m/%Y %H:%M:%S")
png(filename="plot4.png")
par(mfrow=c(2,2))
with(data, {
  plot(x,Global_active_power, type="l", ylab="Global Active Power (kilowatts)", xlab="")
  plot(x, Voltage, type="l", xlab="datetime", ylab="Voltage")
  plot(x,Sub_metering_1, type="l", ylab="Energy sub metering", xlab="")
  lines(x,Sub_metering_2, col="red")
  lines(x,Sub_metering_3, col="blue")
  legend("topright", c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),lwd=c(2.5,2.5,2.5),col=c("black","red","blue"))
  plot(x, Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
})
dev.off()
